Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    # Private network with static IP
    config.vm.network "private_network", ip: "192.168.56.17"

    # Bridged public network (no IP specified)
    config.vm.network "public_network", bridge: true

    config.vm.synced_folder "./scripts", "/scripts"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
end